-- AeroCare Supabase Migration file
-- Translated from SQLite to PostgreSQL

-- Ensure UUID extension is available if needed later
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. events
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'active'
);

-- 2. locations
CREATE TABLE IF NOT EXISTS public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    capacity INTEGER NOT NULL,
    facilities TEXT NOT NULL
);

-- 3. passengers
CREATE TABLE IF NOT EXISTS public.passengers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES public.events (id),
    name TEXT NOT NULL,
    flight_number TEXT,
    country TEXT,
    passport_number TEXT,
    nationality TEXT,
    departure_airline TEXT,
    departure_date TEXT,
    final_destination TEXT,
    location_id BIGINT REFERENCES public.locations (id),
    qr_token TEXT UNIQUE NOT NULL,
    status TEXT NOT NULL DEFAULT 'registered',
    qr_generated_at TIMESTAMPTZ,
    companion_adults INTEGER NOT NULL DEFAULT 0,
    companion_children INTEGER NOT NULL DEFAULT 0,
    tags TEXT DEFAULT ''
);

-- 4. benefits
CREATE TABLE IF NOT EXISTS public.benefits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    value INTEGER NOT NULL,
    picture_url TEXT NOT NULL DEFAULT '',
    available_locations TEXT NOT NULL DEFAULT '',
    open_time TEXT NOT NULL DEFAULT '',
    close_time TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    active INTEGER NOT NULL DEFAULT 1
);

-- 5. passenger_benefits
CREATE TABLE IF NOT EXISTS public.passenger_benefits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id BIGINT NOT NULL REFERENCES public.passengers (id) ON DELETE CASCADE,
    benefit_id BIGINT NOT NULL REFERENCES public.benefits (id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'available'
);

-- 6. transactions
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id BIGINT NOT NULL REFERENCES public.passengers (id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    location_id BIGINT REFERENCES public.locations (id) ON DELETE SET NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 7. messages
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id BIGINT NOT NULL REFERENCES public.passengers (id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    sender TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    status TEXT NOT NULL DEFAULT 'open'
);

-- 8. broadcast_messages
CREATE TABLE IF NOT EXISTS public.broadcast_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    target_type TEXT NOT NULL DEFAULT 'all',
    target_airline TEXT,
    target_destination TEXT,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_by TEXT NOT NULL DEFAULT 'admin'
);

-- 9. dropdown_options
CREATE TABLE IF NOT EXISTS public.dropdown_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    label TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    UNIQUE (category, label)
);

-- 10. app_settings
CREATE TABLE IF NOT EXISTS public.app_settings (
    key TEXT PRIMARY KEY NOT NULL,
    value TEXT NOT NULL
);

-- 11. chat_default_responses
CREATE TABLE IF NOT EXISTS public.chat_default_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'general',
    sort_order INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1
);

-- 12. activity_log
CREATE TABLE IF NOT EXISTS public.activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    description TEXT NOT NULL,
    passenger_id BIGINT REFERENCES public.passengers (id) ON DELETE SET NULL,
    passenger_name TEXT,
    metadata TEXT,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 13. companions
CREATE TABLE IF NOT EXISTS public.companions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id BIGINT NOT NULL REFERENCES public.passengers (id) ON DELETE CASCADE,
    type TEXT NOT NULL DEFAULT 'adult',
    nationality TEXT NOT NULL DEFAULT '',
    passport_number TEXT NOT NULL DEFAULT ''
);

-- 14. admin_users
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT NOT NULL CHECK (
        role IN (
            'monitor',
            'operator',
            'admin'
        )
    ),
    display_name TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1
);

-- 15. building_qr_codes
CREATE TABLE IF NOT EXISTS public.building_qr_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL CHECK (
        type IN ('checkin', 'checkout')
    ),
    label TEXT NOT NULL DEFAULT '',
    location_id BIGINT REFERENCES public.locations (id),
    active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ
);

-- ==========================================
-- Security / Row Level Security (RLS)
-- Optional: Enable RLS and setup policies to secure data.
-- Uncomment if you plan to access the database directly from frontend
-- ==========================================

-- ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.passengers ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.benefits ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.passenger_benefits ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.broadcast_messages ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.dropdown_options ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.chat_default_responses ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.companions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.building_qr_codes ENABLE ROW LEVEL SECURITY;